import { async, ComponentFixture, TestBed } from '@angular/core/testing';
import { MatCardModule } from '@angular/material/card';
import { ActivatedRoute } from '@angular/router';
import { RouterTestingModule } from '@angular/router/testing';
import { ActivatedRouteStub } from '../../testing/activated-route-stub';
import { MockUserService } from '../../testing/user.service.mock';
import { Todo } from './todo';
//import { TodoCardComponent } from './user-card.component';
import { TodoProfileComponent } from './todo-profile.component';
import { TodoService } from './todo.service';
